name: Testomatio Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'Tests to grep (filter by name)'
        required: false
        default: ''
      run:
        description: 'Run a specific command instead of default'
        required: false
      testomatio:
        description: 'Send results to Testomatio'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd unit-integration-tests
          npm install
          npm install @testomatio/reporter --save-dev

      - name: Run tests
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
        run: |
          cd unit-integration-tests
          if [ "${{ github.event.inputs.run }}" != "" ]; then
            echo "Running custom command: ${{ github.event.inputs.run }}"
            eval "${{ github.event.inputs.run }}"
          else
            if [ "${{ github.event.inputs.grep }}" != "" ]; then
              npx jest --grep "${{ github.event.inputs.grep }}" --reporters=default --reporters=@testomatio/reporter
            else
              npx jest --reporters=default --reporters=@testomatio/reporter
            fi
          fi
