name: Testomatio Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep'
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug — show current directory structure
        run: |
          pwd
          ls -R .

      - name: Install dependencies
        run: |
          if [ -f "unit-integration-tests/package.json" ]; then
            echo "Found package.json in unit-integration-tests. Installing dependencies..."
            cd unit-integration-tests
            npm install
          elif [ -f "package.json" ]; then
            echo "Found package.json in project root. Installing dependencies..."
            npm install
          else
            echo "❌ No package.json found in expected locations!"
            exit 1
          fi

      - name: Run tests
        run: |
          if [ -f "unit-integration-tests/package.json" ]; then
            cd unit-integration-tests
            npm test
          elif [ -f "package.json" ]; then
            npm test
          else
            echo "❌ No package.json found — skipping tests."
            exit 1
          fi

      - name: Show test coverage (optional)
        run: |
          if [ -f "unit-integration-tests/package.json" ]; then
            cd unit-integration-tests
            npm test -- --coverage
          elif [ -f "package.json" ]; then
            npm test -- --coverage
          else
            echo "❌ No package.json found — cannot show coverage."
          fi
