name: Node.js CI/CD with Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'Filter tests by name'
        required: false
        default: ''
      run:
        description: 'Alternative test pattern (alias for grep)'
        required: false
        default: ''
      testomatio:
        description: 'Send results to Testomatio'
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit and integration tests
        run: |
          TEST_PATTERN="${{ github.event.inputs.run }}"
          if [ "$TEST_PATTERN" = "" ]; then
            TEST_PATTERN="${{ github.event.inputs.grep }}"
          fi

          if [ "$TEST_PATTERN" != "" ]; then
            echo "Running tests matching pattern: $TEST_PATTERN"
            npx jest unit-integration-tests --grep "$TEST_PATTERN" --coverage
          else
            echo "Running all tests"
            npx jest unit-integration-tests --coverage
          fi

      - name: Send results to Testomatio (optional)
        if: ${{ github.event.inputs.testomatio }}
        run: |
          echo "Sending test results to Testomatio..."
          # Здесь добавь команду интеграции с Testomatio

      - name: Build project
        run: npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_APP_NAME
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
