name: Testomatio Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep'
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd unit-integration-tests && npm install

      - name: Run tests
        run: cd unit-integration-tests && npm test

      - name: Show test coverage (optional)
        run: cd unit-integration-tests && npm test -- --coverage
